[package]
name = "handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.30"
daemonize = "0.5.0"
gtk = "0.15"
notify = "5.1.0"
souvlaki = { version = "0.6.0", default-features = false, features = ["use_zbus"] }
# souvlaki = "0.6.0"
tray-item = "0.7.1"
